### ISSUE TITLE
Improve Delta Acceptance Testing (DAT) automation

### ISSUE THREAD

**Issue by JHibbard** [delta-incubator/deltaray#10]
Create PyTest fixture for deltaray that loops over DAT tests using [this commit](https://github.com/delta-io/delta-rs/commit/b67c602a02dd76d96de500163da490a5abd949d3
) as a reference. The relevant test fixture is [here](https://github.com/delta-io/delta-rs/commit/b67c602a02dd76d96de500163da490a5abd949d3#diff-5c31bbdc2653d366be44aa1406942f468db69b61954a9e2aa01cbf937afa79fdR12-R43).

For added context, DAT's tests are a collection of Delta tables and parquet files that readers ingest and compare by asserting they are equivalent. The DAT directory structure is consistent and looping over the directory structure enumerates all the test cases. The PyTest fixture will accept a root path for a DAT directory and step through it to find each test case. For each test case present the framework being tested will read the parquet and Delta table(s) associated with the tests and compare them.

If [PR-11](https://github.com/delta-incubator/deltaray/pull/11) is merged it will provide DAT testing automation and cover the following DAT tables:
- all_primitive_types
- basic_append
- basic_partitioned
- no_replay
- stats_as_struct
- with_checkpoint
- with_schema_change

[PR-11](https://github.com/delta-incubator/deltaray/pull/11) wont cover all DAT tables due to upstream issues, for more details see [Issue 12](https://github.com/delta-incubator/deltaray/issues/12) for ongoing DAT coverage tracking. These tables wont be covered:
- multi_partitioned
- multi_partitioned_2
- nested_types
- no_stats

**Comment by JHibbard** [comment]
For added context, `deltaray` does not currently use all test cases provided by the [Delta Acceptance Testing (DAT)](https://github.com/delta-incubator/dat) project. DAT provides a collection of Parquet and Delta tables that can be used to verify different implementations of Delta Lake readers and writers all behave consistently. We want to reach full coverage of DAT tests within `deltaray` so that we can help ensure error free interoperability with the entire Delta Lake ecosystem.

  `deltaray` only uses the following test cases from DAT:
  - all_primitive_types

  `deltaray` needs to test these additional DAT tables:
  - basic_append
  - basic_partitioned
  - multi_partitioned
  - multi_partitioned_2
  - nested_types
  - no_replay
  - no_stats
  - stats_as_struct
  - with_checkpoint
  - with_schema_change

**Comment by dennyglee** [comment]
Thanks @JHibbard  - feel free to close this issue as I think #11 resolves all of this - awesome!

**Comment by JHibbard** [comment]
Excellent, closed with [PR-11](https://github.com/delta-incubator/deltaray/pull/11).
