### ISSUE TITLE
Add Delta Acceptance Testing (DAT) to this project with reader tests

### ISSUE THREAD

**Issue by MrPowers** [delta-incubator/deltaray#3]
DAT defines a bunch of Delta reference tables and reader tests that'd be great for this project.  Here's the link to DAT: https://github.com/delta-incubator/dat

Can we add DAT and the reader tests?

**Comment by JHibbard** [comment]
Sure thing, this is a great idea! [PR-11](https://github.com/delta-incubator/deltaray/pull/11) should partially address this, we will also track any DAT tables we are unable to test or not currently testing in [issue 12](https://github.com/delta-incubator/deltaray/issues/12). Thanks!

**Comment by JHibbard** [comment]
@MrPowers I think we can close this now that [PR-11](https://github.com/delta-incubator/deltaray/pull/11) is merged? We'll continue tracking DAT coverage in [issue 12](https://github.com/delta-incubator/deltaray/issues/12). Let me know if we need to reopen this for any reason. Thanks!
